package main

import (
	"os"
	"reflect"
	"strings"
	"testing"
)

func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o644)
}

func commentCount(t *testing.T, src string) int {
	t.Helper()
	return commentCountIn(t, "src_test.go", src)
}

func commentCountIn(t *testing.T, path, src string) int {
	t.Helper()
	skip, s, err := scanFile([]byte(src), path)
	if err != nil {
		t.Fatalf("scanFile(%q): %v", src, err)
	}
	if skip {
		return 0
	}
	return len(s.comments)
}

func TestLineCommentsCount(t *testing.T) {
	for _, tc := range []struct {
		src  string
		want int
	}{
		{"package p\n\nvar x = 1\n", 0},
		{"package p\n// line\nvar x = 1 // trailing\n", 2},
		{"// Foo does things.\npackage p\n", 1},
		{"package p\n\n/* one */ var x = 1 /* two */\n", 2},
		{"package p\n\n/* // inert */ var x = 1\n", 1},
		{"// /* inert\npackage p\n", 1},
		{"package p\n\nvar s = \"// not a comment /* nor this */\"\n", 0},
		{"package p\n\nvar s = `// not a comment\n/* nor this */`\n", 0},
		{"package p\n\nvar c = '/'\nvar u = 'ሴ'\n", 0},
		{"package p\n\nvar e = '\\n'\nvar q = '\\''\nvar b = '\\\\'\n", 0},
		{"package p\n\nvar x = 1 /* a /* b */ + 2\n", 1},
		{"package p\n\nvar x = 1 /* a /* b */ + 2 // real\n", 2},
		{"package p\n\nvar x = 1 /* a /* b */ + 2\nvar s = \"// found\"\n", 1},
		{"//go:build ignore\n\npackage p\n", 0},
		{"\uFEFF//go:build impossible_tag\n\npackage p\n", 0},
		{"\uFEFF// +build impossible_tag\n\npackage p\n", 0},
		{"\uFEFF//line fake.go:100\npackage p\n", 1},
		{"\uFEFF//go:generate mockgen\npackage p\n", 1},
		{"package p\n\n//go:embed foo.txt\nvar embedded string\n", 0},
		{"//go:generate stringer -type=Kind\npackage p\n", 0},
		{"package p\n\nvar x = 1 //nolint:gocyclo\n", 0},
		{"package p\n\nvar x = 1 //nolint\n", 0},
		{"package p\n\nvar x = 1 // go:build\n", 1},
		{"package p\n\nvar x = 1 //go:buildozer\n", 1},
		{"package p\n\nvar x = 1 //nolintx\n", 1},
		{"package p\n\n/*nolint*/\n", 1},
		{"//go:generate: explanation\npackage p\n", 1},
		{"//nolint-anything\npackage p\n", 1},
		{"//nolint:\npackage p\n", 1},
		{"//nolint:,\npackage p\n", 1},
		{"//nolint:foo!\npackage p\n", 1},
		{"//go:generate mockgen -source a.go\npackage p\n", 0},
		{"//go:build linux && !darwin\n\npackage p\n", 0},
		{"//go:embed model/*.gguf\npackage p\n", 0},
		{"//go:build\n\npackage p\n", 0},
		{"package p\n\nvar x = 1 //nolint:gocyclo,goconst // rationale\n", 0},
		{"package p\n\nvar x = 1 //nolint // reason\n", 0},
		{"package p\n\n  //go:nointerface\nfunc (t T) M() {}\n", 0},
		{"package p\n\n  //go:registerparams\nfunc r() {}\n", 0},
		{"package p\n\n  //go:debug madvdontneed=1\nfunc d() {}\n", 1},
		{"//go:build linux\r\n\r\npackage p\r\n", 0},
		{"//line fake.go:100:20\n//go:build impossible_tag\n\npackage p\n", 0},
		{"// +build impossible_tag\n\npackage p\n", 0},
		{"// +build impossible_tag\npackage p\n", 1},
		{"  //go:build impossible_tag\n\npackage p\n", 0},
		{" //go:build impossible_tag\n\npackage p\n", 0},
		{"//go:build impossible_tag\n\npackage p\n", 0},
		{"// +build impossible_tag\n\npackage p\n", 0},
		{"\t//go:build impossible_tag\n\npackage p\n", 0},
		{"  // +build impossible_tag\n\npackage p\n", 0},
		{"/*\n// Code generated by x. DO NOT EDIT.\n*/\n// +build impossible_tag\n\npackage p\n", 1},
		{"// +build impossible_tag\n/*\n// Code generated by x. DO NOT EDIT.\n*/\n\npackage p\n", 1},
		{"/*\n// Code generated by x. DO NOT EDIT.\n*/ //go:build impossible_tag\n\npackage p\n", 1},
		{"//+build impossible_tag\n\npackage p\n", 0},
		{"//   +build impossible_tag\n\npackage p\n", 0},
		{"//+buildnote\n\npackage p\n", 1},
		{"package p\n\nvar x = 1 // +build note\n", 1},
		{"package p\n\n// +build impossible_tag\nvar x = 1\n", 1},
		{"package p\n\n//go:build impossible_tag\nvar x = 1\n", 1},
		{"package p\n\nvar x = /*line gen\nfile.go:42*/ 1\n", 0},
		{"package p\n\nfunc f() {\n\t// +build indented\n}\n", 1},
		{"/*line generated.go:42*/\npackage p\n", 0},
		{"package p\n\nvar x = /*line g.go:5*/ 1\n", 0},
		{"package p\n\nvar x = /*line generated file.go:42*/ 1\n", 0},
		{"/* liner note */\npackage p\n", 1},
		{"/* lineage */\npackage p\n", 1},
		{"package p\n\nvar (\n\t//go:generate echo x\n\tX int\n)\n", 1},
		{"package p\n\nvar (\n\t//go:embed data.txt\n\tS string\n)\n", 0},
		{"package p\n\nvar x = 1 //nolint:gocyclo\r\n", 0},
		{"// plain crlf comment\r\npackage p\r\n", 1},
		{"package p\n\nfunc f() {\n\t//go:generate echo ignored\n}\n", 1},
		{"package p\n\nvar x = 1 //go:generate echo\n", 1},
		{"package p\n\nfunc f() {\n\t//nolint:gocyclo\n}\n", 0},
		{"package p\n\nvar (\n\t//go:embed data.txt\n\tS string\n)\n", 0},
		{"package p\n\nvar x = 1 //go:embed data.txt\n", 1},
		{"package p\n\n/*\n#include <stdlib.h>\n*/\nimport \"C\"\n", 0},
		{"package p\n\n// #include <stdio.h>\nimport \"C\"\n", 0},
		{"package p\n\n// #cgo CFLAGS: -DX\n// #include <x.h>\nimport \"C\"\n", 0},
		{"package p\n\n/*\n#include <stdlib.h>\n*/\nimport (\n\t\"C\"\n)\n", 0},
		{"package p\n\n/* not a preamble above a multi-spec block */\nimport (\n\t\"C\"\n\t_ \"fmt\"\n)\n", 1},
		{"package p\n\nimport (\n\t// #include <stdio.h>\n\t\"C\"\n\t_ \"fmt\"\n)\n", 0},
		{"package p\n\n/*\n#include <stdlib.h>\n*/\n\nimport \"C\"\n", 1},
		{"package p\n\n/* plain doc */\nimport \"os\"\n", 1},
		{"package p\n\n//go:linkname foo bar\nvar x = 1\n", 0},
		{"package p\n\n  //go:linkname local remote\n\nvar local int\n", 0},
		{"package p\n\nfunc f() {\n\t//go:noinline\n\t_ = 1\n}\n", 1},
		{"package p\n\n//go:nosplit\nfunc g() {}\n", 0},
		{"package p\n\n//go:uintptrescapes\nfunc h() {}\n", 0},
		{"//go:debug madvdontneed=1\npackage main\n", 0},
		{"  //go:debug panicnil=1\npackage main\n", 0},
		{"package main\n\n//go:debug x=1\nvar x int\n", 1},
		{"//go:norace\npackage p\n", 0},
		{"package p\n\n//go:noescape\nfunc e() {}\n", 0},
		{"package p\n\n//go:wasmimport env host1\nfunc w() {}\n", 0},
		{"package p\n\n  //go:wasmexport hello\nfunc x() {}\n", 0},
		{"package p\n\n  //go:noescape\nfunc i() {}\n", 0},
		{"//line file.go:10\npackage p\n", 0},
		{"//line just prose\npackage p\n", 1},
		{"package p\n\nfunc f() {\n\t//line x.go:1\n\t_ = 1\n}\n", 1},
		{"package p\n\nimport \"C\"\n\n//export MyFunc\nfunc MyFunc() {}\n", 0},
		{"package p\n\n//export MyFunc\nfunc MyFunc() {}\n", 1},
		{"package p\n\n//export\tMyFunc\nfunc MyFunc() {}\n", 1},
		{"package p\n\n//export\nfunc F() {}\n", 1},
		{"package p\n\n//export X\nvar X int\n", 1},
		{"package p\n\n//export T\ntype T struct{}\n", 1},
		{"package p\n\n//go:noinlinex\nfunc k() {}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc ExampleGreeting() {\n\tfmt.Println(\"hi\")\n\n\t// Output: hi\n}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc Example() {\n\tfmt.Println(1)\n\t// Output:\n\t// 1\n}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc Example() {\n\tfmt.Println(1)\n\t// Unordered output:\n\t// one\n\t// two\n}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc Example() {\n\t// Output: buried\n\tfmt.Println(1)\n\t// note\n}\n", 2},
		{"package p\n\nimport \"fmt\"\n\nfunc f() {\n\tfmt.Println(1)\n\t// Output: not an example\n}\n", 1},
		{"package p\n\nimport \"fmt\"\n\nfunc Example() {\n\tfmt.Println(1)\n\t/* Output: 1 */\n}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc Example() {\n\tfmt.Println(1)\n\t//\n\t// Output: 1\n}\n", 0},
		{"package p\n\nimport \"fmt\"\n\nfunc Examplefoo() {\n\tfmt.Println(1)\n\t// Output: 1\n}\n", 1},
		{"package p\n\nimport \"fmt\"\n\nfunc Example(x int) {\n\tfmt.Println(x)\n\t// Output: 1\n}\n", 1},
		{"// Code generated by tool. DO NOT EDIT.\n\npackage p\n", 0},
		{"// Code generated by tool. DO NOT EDIT.\r\n\r\npackage p\r\n", 0},
		{"// Code gen\rerated by tool. DO NOT EDIT.\n\npackage p\n", 0},
		{"// Code generated by tool.\n\npackage p\n", 1},
		{"package p\n\n// Code generated by tool. DO NOT EDIT.\nvar x = 1\n", 1},
		{"/*\n// Code generated by tool. DO NOT EDIT.\n*/\npackage p\n", 0},
	} {
		if got := commentCount(t, tc.src); got != tc.want {
			t.Errorf("scanSource(%q) counted %d comments, want %d", tc.src, got, tc.want)
		}
	}
	if got := commentCountIn(t, "src.go", "package p\n\nimport \"fmt\"\n\nfunc Example() {\n\tfmt.Println(1)\n\t// Output: 1\n}\n"); got != 1 {
		t.Errorf("non-test file example output counted %d, want 1", got)
	}
}

func TestScanRefusals(t *testing.T) {
	for _, tc := range []struct {
		src  string
		want string
	}{
		{"package p\n\nvar x = 1 /* never closed\n", "unparseable"},
		{"package p\n\nvar s = \"abc\n", "unparseable"},
		{"package p\n\nvar s = `raw never closed\n", "unparseable"},
		{"package p\n\nvar n = 1/**/.5\n", "unparseable"},
		{"var x = 1\n", "unparseable"},
		{"package p\n\nvar x = 1\n\uFEFF// mid-file bom\n", "unparseable"},
	} {
		if _, err := scanSource([]byte(tc.src), "src.go"); err == nil || !strings.Contains(err.Error(), tc.want) {
			t.Errorf("scanSource(%q) err = %v, want containing %q", tc.src, err, tc.want)
		}
	}
}

func TestJudge(t *testing.T) {
	allow := map[string]int{"a.go": 5}
	for _, tc := range []struct {
		file  string
		count int
		ok    bool
	}{
		{"a.go", 0, true},
		{"b.go", 0, true},
		{"b.go", 1, false},
		{"a.go", 5, true},
		{"a.go", 4, true},
		{"a.go", 6, false},
	} {
		if msg := judge(tc.file, tc.count, allow); (msg == "") != tc.ok {
			t.Errorf("judge(%q, %d) = %q, want ok=%v", tc.file, tc.count, msg, tc.ok)
		}
	}
	if msg := judge("b.go", 2, allow); !strings.Contains(msg, "non-allowlisted") {
		t.Errorf("judge non-allowlisted msg = %q", msg)
	}
	if msg := judge("a.go", 6, allow); !strings.Contains(msg, "increased") {
		t.Errorf("judge increased msg = %q", msg)
	}
}

func TestReadAllowlistMissing(t *testing.T) {
	allow, err := readAllowlist(t.TempDir() + "/absent.txt")
	if err != nil {
		t.Fatal(err)
	}
	if len(allow) != 0 {
		t.Errorf("want empty allowlist, got %v", allow)
	}
}

func TestReadAllowlistParse(t *testing.T) {
	path := t.TempDir() + "/allow.txt"
	content := "# seeded at landing\n\ninternal/store/store.go:12\nweird/dir:2 x.go:3\n"
	if err := writeFile(path, content); err != nil {
		t.Fatal(err)
	}
	allow, err := readAllowlist(path)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]int{"internal/store/store.go": 12, "weird/dir:2 x.go": 3}
	if !reflect.DeepEqual(allow, want) {
		t.Errorf("allow = %v, want %v", allow, want)
	}
}

func TestReadAllowlistMalformed(t *testing.T) {
	path := t.TempDir() + "/allow.txt"
	if err := writeFile(path, "internal/store/store.go\n"); err != nil {
		t.Fatal(err)
	}
	if _, err := readAllowlist(path); err == nil {
		t.Error("want error for entry without count")
	}
}
